version: "3.9"
services:
  jwt_auth_golang:
    build: .
    ports:
      - '80:9000'
    links:
      - "postgresdb"
  postgresdb:
    image: "postgres"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Secret123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
